# Generated by Django 2.1.4 on 2019-01-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=200)),
                ('authername', models.CharField(max_length=200)),
                ('publication', models.CharField(max_length=200)),
                ('classname', models.IntegerField()),
                ('departmentname', models.CharField(max_length=200)),
            ],
        ),
    ]
