# Generated by Django 2.1.4 on 2019-01-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookModel', '0002_auto_20190122_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='authername',
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='bookname',
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='classname',
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='departmentname',
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='publication',
        ),
    ]
