# Generated by Django 2.1.4 on 2019-01-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookModel', '0003_auto_20190122_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='coursename',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='feedback',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
